name: Check Code Complexity
on: [push, pull_request]

jobs:
  complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: complexipy
      uses: rohaquinlop/complexipy-action@v3
      with:
        paths: .